# Generated by Django 5.0 on 2024-02-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Moderate'), (3, 'Important'), (4, 'Urgent'), (5, 'Very Urgent')], default=1),
        ),
    ]
