# Generated by Django 5.0 on 2024-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[('Regular', 'Regular'), ('Moderate', 'Moderate'), ('Important', 'Important'), ('Urgent', 'Urgent'), ('Very Urgent', 'Very Urgent')], default=1),
        ),
    ]
