# Generated by Django 5.0 on 2024-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Moderate', 'Moderate'), ('Important', 'Important'), ('Urgent', 'Urgent'), ('Very Urgent', 'Very Urgent')], default='Regular', max_length=20),
        ),
    ]
