# Generated by Django 5.0 on 2024-04-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_prioritychoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
