# Generated by Django 5.0 on 2024-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritychoices',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.ManyToManyField(default=1, to='todo.prioritychoices'),
        ),
    ]
