# Generated by Django 5.0 on 2024-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_prioritychoices_slug_remove_todo_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.ManyToManyField(blank=True, null=True, to='todo.prioritychoices'),
        ),
    ]
