# Generated by Django 5.0 on 2024-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_remove_todo_priority_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
