# Generated by Django 5.0 on 2024-07-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.URLField(blank=True, default='https://static.vecteezy.com/system/resources/thumbnails/005/129/844/small_2x/profile-user-icon-isolated-on-white-background-eps10-free-vector.jpg', null=True),
        ),
    ]
